from typing import Tuple

class RegisteredBuffer:
    @property
    def addr(self) -> int: ...
    @property
    def size(self) -> int: ...

class Transport:
    def listen(self, port: int) -> int: ...
    def accept(self) -> int: ...
    def connect(self, host: str, port: int) -> int: ...
    def close(self) -> None: ...
    def reg_buf(self, buf: object) -> RegisteredBuffer: ...
    def send_async(
        self, mr: RegisteredBuffer, len: int, id: int = 0, offset: int = 0
    ) -> None: ...
    def recv_async(
        self, mr: RegisteredBuffer, len: int, id: int = 0, offset: int = 0
    ) -> None: ...
    def poll(self) -> int: ...
    def exchange_buf(self, mr: RegisteredBuffer) -> Tuple[int, int]: ...
    def write_async(
        self,
        mr: RegisteredBuffer,
        remote_addr: int,
        rkey: int,
        len: int,
        id: int = 0,
        offset: int = 0,
    ) -> None: ...
    def read_async(
        self,
        mr: RegisteredBuffer,
        remote_addr: int,
        rkey: int,
        len: int,
        id: int = 0,
        offset: int = 0,
    ) -> None: ...

def create_rdma() -> Transport: ...
def create_tcp() -> Transport: ...
